name: corbado_frontend_api_client
description: Corbado API flutter client
homepage: https://docs.corbado.com/overview/welcome
repository: https://github.com/corbado/flutter-passkeys/tree/main/packages/corbado_api_client
version: 0.1.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  openapi_generator_annotations: ^4.10.0
  http: '>=0.13.0 <0.14.0'
  intl: '^0.17.0'
  meta: '^1.1.8'

dev_dependencies:
  openapi_generator: ^4.10.0
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
